backend:
  name: github
  repo: jerryhub366/buyside-research
  branch: main
  base_url: https://bs.ladebuid.com
  auth_endpoint: api/auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "reports"
    label: "研究报告"
    label_singular: "报告"
    folder: "content/reports"
    create: true
    fields:
      - label: "正文内容"
        name: "body"
        widget: "markdown"
